aliases:
    fleeks: cd ~/src/github.com/rastasheep/dotfiles
    apply-mbp: nix run github:ublue-os/fleek -- apply -l src/github.com/rastasheep/dotfiles
    dc: docker compose
    ack: ag
    e: vim
    g: git
    ..: cd ..
    ll: ls -lah
    f: fg
    j: jobs
    df: df -hT
    history: fc -El 1
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: src/github.com/rastasheep/dotfiles
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - silver-searcher
    - coreutils
    - openssl
    - tree
    - docker
    - slack
    - wget
    - zoom-us
    - spotify
    - raycast
    # unsupported apps
    # - arc
    # - _1password-gui-beta
    # - backblaze
    # - blender
    # - google-drive
    # - krita
    # - prusa-slicer
    # - robo3t
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: aarch64
      hostname: aleksandars-mbp
      os: darwin
      username: rastasheep
track: nixos-unstable
unfree: true
users:
    - email: rastasheep3@gmail.com
      name: Aleksandar Diklic
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: rastasheep
