[catalogConfiguration]
customItems = []
folderDepthOverrides = []
scriptsDirectories = []

    [[catalogConfiguration.customFolders]]
    depthRawValue = 1
    entryType = 'directory'
    id = '5242EA7A-D7B1-4169-B548-711BA55534C6'
    path = '~/.nix-profile/bin'

[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.effects'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.emoji'

        [catalogs.globalScopes.scope]
        kind = 'none'

[[comboMode.bindings]]
key = '`'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open-url'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'url:https://github.com/FlorenceHC' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '1'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open-url'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'url:https://mail.google.com/mail/u/0/#inbox' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '2'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open-url'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'url:https://mail.google.com/mail/u/1/?ogbl#inbox' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = '3'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open-url'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'url:https://calendar.google.com/calendar/u/1/r?pli=1' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'a'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.smart-links.actions/send-to-smart-link'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.current-selection/Current Selection' ]
        targetIdentifier = 'tuna.smart-links/Google AI'
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'b'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Safari.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'c'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Applications/Claude.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'enter'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/switch'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.modes/search' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'f'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/run'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.window-management/center-two-thirds' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'g'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.smart-links.actions/send-to-smart-link'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.current-selection/Current Selection' ]
        targetIdentifier = 'tuna.smart-links/GitHub'
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'h'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/run'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.window-management/left-half' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'i'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/System/Applications/Music.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'j'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/run'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.window-management/bottom-left-quarter' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'k'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/run'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.window-management/top-left-quarter' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'l'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/run'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.window-management/right-half' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'm'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open-url'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'url:http://meet.google.com/new?authuser=aleksandar.diklic@florencehc.com' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'S'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/switch'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.modes/talk' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 's'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/rastasheep/.nix-profile/Applications/Slack.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 't'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/open'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'path:/Users/rastasheep/.nix-profile/Applications/Ghostty.app' ]
        type = 'savedCommand'

[[comboMode.bindings]]
key = 'tab'

    [comboMode.bindings.destination]
    type = 'command'

        [comboMode.bindings.destination.command]
        actionIdentifier = 'tuna.common-actions/browse'
        behavior = 'run'
        presentation = 'automatic'
        subjectIdentifiers = [ 'tuna.windows.search/allWindows.search' ]
        type = 'savedCommand'

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256

    [hotkeys.app.comboMode]
    carbonKeyCode = 111
    carbonModifiers = 0

    [hotkeys.app.stageFinderSelection]
    carbonKeyCode = 45
    carbonModifiers = 6912

[settings]
clipboardIgnoredBundleIdentifiers = [ 'com.1password.1password' ]
comboModeModifierTrigger = 'hyper'
comboModeThemeStyle = 'breadcrumb'
dictationWindowPosition = 'bottomLeft'
physicalHyperKeyQuickPressBehavior = 'triggersEscape'
shelfAutoCloseWhenTasksComplete = true
showResultsImmediatelyOnActivation = true
spacebarBehavior = 'switchToTextMode'
switchToTextModeWhenNoResults = true
talkModeDoublePressTrigger = 'rightCommand'
talkModeModifierTrigger = 'rightCommandOption'
talkModeTriggerType = 'modifier'
textModeTriggerType = 'disabled'

[[smartLinks.entries]]
enabled = true
name = 'GitHub'
requiresInput = true
template = 'https://github.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Google'
requiresInput = true
template = 'https://www.google.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Google AI'
requiresInput = true
template = 'https://www.google.com/search?q={{input}}&udm=50'

[[smartLinks.entries]]
enabled = true
name = 'Stack Overflow'
requiresInput = true
template = 'https://stackoverflow.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'Wikipedia'
requiresInput = true
template = 'https://en.wikipedia.org/wiki/Special:Search?search={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'YouTube'
requiresInput = true
template = 'https://www.youtube.com/results?search_query={{input}}'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'

[[catalogSettings]]
catalogIdentifier = 'tuna.prompts'

    [catalogSettings.values]
    Provider = 'apple'

[[catalogSettings]]
catalogIdentifier = 'tuna.text-actions'

    [catalogSettings.values]
    TextActionsFileExtension = 'txt'

[[catalogSettings]]
catalogIdentifier = 'tuna.window-management'

    [catalogSettings.values]
    Cycling = 'sizes'
